<?php
return [
    'type'            => 'mysql',
    'hostname'        => 'localhost',
    'database'        => 'www_kuhukeji_com',
    'username'        => 'www_kuhukeji_com',
    'password'        => 'i4DNNZy5Ps7DLXAJ',
    'hostport'        => '3306',
    'dsn'             => '',
    'params'          => [],
    'charset'         => 'utf8',
    'prefix'          => 'wyu_',
    'debug'           => false,
    'deploy'          => 0,
    'rw_separate'     => false,
    'master_num'      => 1,
    'slave_no'        => '',
    'read_master'     => false,
    'fields_strict'   => true,
    'resultset_type'  => 'array',
    'auto_timestamp'  => false,
    'datetime_format' => 'Y-m-d H:i:s',
    'sql_explain'     => false,
];
